### ISSUE TITLE
Hero's Attack function fails to damage target

### ISSUE THREAD

**Issue by EmoBurrito** [EmoBurrito/oChre#1]
As the title says, the hero class's attack function doesn't seem to actually be damaging the target. I tested to see if the ouch function can be invoked to damage the target directly and it can, leading me to believe there is an issue with the attack function itself.

**Comment by LIQRGV** [comment]
I think, instead of pass by value, you should pass Hero by reference.
Maybe change 
`void attack(Hero target)` into `void attack(Hero &target)` ?
